Updates from Jason:
FileErrorManager capture LinkageError from File.deleteOnExit.
LogManagerProperties new create object factory methods.
LogManagerProperties add toLanguageTag method.
LogManagerProperties prevent escaping of static init runtime exceptions.
LogManagerProperties override more properties methods to cache values.
LogManagerPropertiesTest new object factory tests.
LogManagerPropertiesTest more properties method testing.
LogManagerPropertiesTest added PropUtil test.
MailHandler convert java charsets to mime charsets.
MailHandler fixed IllegalStateException when NoClassDefFoundError was thrown.
MailHandler refactor LogManager object init code.
MailHandler add Incomplete-Copy header when parts are omitted by formatters.
MailHandler map Accept-Language header to Locale.getDefault()
MailHandler map Content-Language header if LogRecord has a ResourceBundle.
MailHandler Message description should include comparator class and push info.
MailHandler Mime part description should include formatter name class.
MailHandler additional verify checks for SendFailedException.
MailHandlerTest tests for attachment invariants.
MailHandlerTest tests for creating classes where the constructor throws.
MailHandlerTest tests for creating classes where the static init throws.
MailHandlerTest tests for content and accept language headers.
MailHandlerTest tests for content description for all parts and mime message.